cc_binary(
    name = "default",
    srcs = ["default.cpp"],
)

cc_binary(
    name = "typetrait",
    srcs = ["typetrait.cpp"],
)

cc_binary(
    name = "typetrait2",
    srcs = ["typetrait2.cpp"],
)

cc_binary(
    name = "typetrait3",
    srcs = ["typetrait3.cpp"],
)

cc_binary(
    name = "typetrait4",
    srcs = ["typetrait4.cpp"],
)

cc_binary(
    name = "typetrait5",
    srcs = ["typetrait5.cpp"],
)

cc_binary(
    name = "special_base",
    srcs = ["special_base.cpp"],
)

cc_binary(
    name = "special_partial",
    srcs = ["special_partial.cpp"],
)

cc_binary(
    name = "special_explicit",
    srcs = ["special_explicit.cpp"],
)

cc_binary(
    name = "variadic",
    srcs = ["variadic.cpp"],
)

cc_binary(
    name = "membertemp",
    srcs = ["membertemp.cpp"],
)

cc_binary(
    name = "ttp",
    srcs = ["ttp.cpp"],
)

cc_binary(
    name = "ttp2",
    srcs = ["ttp2.cpp"],
)
