cc_binary(
    name = "rope_user",
    srcs = ["rope_user.cpp"],
    deps = [
        ":rope",
    ],
)

cc_library(
    name = "rope",
    srcs = ["rope.cpp"],
    hdrs = ["rope.h"],
    deps = [],
)
