cc_binary(
    name = "addnumbers",
    srcs = ["addnumbers.cpp"],
    deps = [],
)

cc_binary(
    name = "cat",
    srcs = ["cat.cpp"],
    deps = [],
)

cc_binary(
    name = "sort3",
    srcs = ["sort3.cpp"],
    deps = [],
)
