cc_binary(
    name = "operators",
    srcs = ["operators.cpp"],
    deps = [],
)

cc_binary(
    name = "processes",
    srcs = ["processes.cpp"],
    deps = [],
)

cc_binary(
    name = "reader",
    srcs = ["reader.cpp"],
    deps = [],
)
