cc_library(
    name = "string_view",
    srcs = ["string_view.cpp"],
    hdrs = ["string_view.h"],
    deps = [],
)

cc_test(
    name = "string_view_test",
    srcs = ["string_view_test.cpp"],
    deps = [
        ":string_view",
        "//:catch",
    ],
)
