cc_library(
    name = "types",
    srcs = [],
    hdrs = ["types.h"],
    deps = [],
)

cc_binary(
    name = "first",
    srcs = ["first.cpp"],
    deps = [
        ":types",
    ],
)

cc_binary(
    name = "second",
    srcs = ["second.cpp"],
    deps = [
        ":types",
    ],
)

cc_binary(
    name = "third",
    srcs = ["third.cpp"],
    deps = [
        ":types",
    ],
)

cc_binary(
    name = "fourth",
    srcs = ["fourth.cpp"],
    deps = [
        ":types",
    ],
)
