cc_binary(
    name = "bookstore_main",
    srcs = ["bookstore_main.cpp"],
    deps = [
        ":bookstore",
    ],
)

cc_library(
    name = "bookstore",
    srcs = ["bookstore.cpp"],
    hdrs = ["bookstore.h"],
    deps = [],
)
