cc_binary(
    name = "point1",
    srcs = ["point1.cpp"],
    deps = [],
)

cc_binary(
    name = "point2",
    srcs = ["point2.cpp"],
    deps = [],
)

cc_binary(
    name = "arrow",
    srcs = ["arrow.cpp"],
    deps = [],
)

cc_binary(
    name = "io",
    srcs = ["io.cpp"],
    deps = [],
)

cc_binary(
    name = "incdec",
    srcs = ["incdec.cpp"],
    deps = [],
)

cc_binary(
    name = "type",
    srcs = ["type.cpp"],
    deps = [],
)

